// Builds the Watch & Bet odds table: plays thousands of headless bot-vs-bot
// games (watch mode, with form and momentum, exactly as you see them) for
// every pair of bots and writes one record per game to src/odds-data.js.
//
//   node tools/odds.mjs [games per pair] [games per mirror pair] [--validate]
//
// --validate also plays real best-of-3 and best-of-5 matches for a few pairs
// and compares them with the odds the game derives from single games.
import { Worker, isMainThread, parentPort, workerData } from 'node:worker_threads';
import { writeFileSync } from 'node:fs';
import { cpus } from 'node:os';
import { fileURLToPath } from 'node:url';
import * as THREE from 'three';
import { Game } from '../src/game.js';
import { OPPONENTS, PLAYER, AI } from '../src/config.js';

// One game record in 3 base64url characters (18 bits):
//   bit 0      the lower-numbered bot won
//   bits 1-6   the loser's score (the winner's is 11, or loser + 2 at deuce)
//   bits 7-17  the longest rally
const B64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
const encode = (won, lose, longest) => {
  const v = (won ? 1 : 0) | (Math.min(lose, 63) << 1) | (Math.min(longest, 2047) << 7);
  return B64[v & 63] + B64[(v >> 6) & 63] + B64[(v >> 12) & 63];
};

function makeGame() {
  const noop = new Proxy({}, { get: () => () => {} });
  const world = { scene: new THREE.Scene(), camera: new THREE.PerspectiveCamera(), update() {}, drawScreen() {}, pointScale: () => 800 };
  const input = { isDown: () => false, wasPressed: () => false, mouseDown: [0, 0, 0], mousePressed: [0, 0, 0] };
  const game = new Game(world, noop, noop, input, { quality: 'low', difficulty: 0, matchLength: 1 });
  game.updateVisuals = () => {};
  game.onWatchEnd = () => {};
  return game;
}

// Plays one match (bot a near or far, alternating) and reports it from a's side.
function play(game, a, b, length, aNear) {
  game.startWatch(aNear ? a : b, aNear ? b : a, length);
  game.setFast(true);
  for (let steps = 0; game.state !== 'over' && steps < 120 * 7200; steps++) game.update(1 / 120);
  const aSide = aNear ? PLAYER : AI;
  const m = game.match;
  const h = m.history[0];
  return {
    aWon: m.winner === aSide,
    lose: Math.min(h[PLAYER], h[AI]),
    longest: game.wstats.longest,
    games: m.games[aSide],
  };
}

if (!isMainThread) {
  const game = makeGame();
  for (const job of workerData.jobs) {
    const { a, b, n, length } = job;
    let rec = '';
    let wins = 0;
    for (let i = 0; i < n; i++) {
      const r = play(game, a, b, length, i % 2 === 0);
      if (r.aWon) wins++;
      if (length === 1) rec += encode(r.aWon, r.lose, r.longest);
    }
    parentPort.postMessage({ ...job, wins, rec });
  }
} else {
  const args = process.argv.slice(2);
  const validate = args.includes('--validate');
  const nums = args.filter((x) => !x.startsWith('--')).map(Number);
  const N = nums[0] || 3000;
  const NM = nums[1] || 2000;
  const jobs = [];
  // Split each pair into chunks so all the cores stay busy.
  const CHUNK = 250;
  for (let a = 0; a < OPPONENTS.length; a++) {
    for (let b = a; b < OPPONENTS.length; b++) {
      const n = a === b ? NM : N;
      for (let k = 0; k < n; k += CHUNK) jobs.push({ a, b, n: Math.min(CHUNK, n - k), length: 1 });
    }
  }
  if (validate) {
    for (const [a, b] of [[1, 2], [2, 3], [3, 4], [2, 2]]) {
      for (const length of [2, 3]) for (let k = 0; k < 400; k += 100) jobs.push({ a, b, n: 100, length });
    }
  }
  // Longest jobs (ZERO's long rallies) first.
  jobs.sort((x, y) => (y.length * 10 + y.b + y.a) - (x.length * 10 + x.b + x.a));
  const W = Math.max(1, cpus().length);
  const queues = Array.from({ length: W }, () => []);
  jobs.forEach((j, i) => queues[i % W].push(j));
  const t0 = Date.now();
  const results = [];
  await Promise.all(queues.map((q) => new Promise((resolve, reject) => {
    const w = new Worker(fileURLToPath(import.meta.url), { workerData: { jobs: q } });
    w.on('message', (m) => {
      results.push(m);
      process.stderr.write(`\r${results.length}/${jobs.length} chunks, ${((Date.now() - t0) / 1000).toFixed(0)} s   `);
    });
    w.on('error', reject);
    w.on('exit', resolve);
  })));
  process.stderr.write('\n');

  const games = {};
  const tally = {};
  for (const r of results.filter((x) => x.length === 1)) {
    const key = `${r.a}-${r.b}`;
    games[key] = (games[key] || '') + r.rec;
    tally[key] = tally[key] || { n: 0, wins: 0 };
    tally[key].n += r.n;
    tally[key].wins += r.wins;
  }
  const out = `// Generated by tools/odds.mjs on ${new Date().toISOString().slice(0, 10)}: ${N} headless watch-mode
// games for each pair of bots (${NM} for each mirror pair). Do not edit by hand.
// games['a-b'] (a <= b, ladder order) holds one 3-character record per game:
// 18 bits = [bot a won: 1][loser's score: 6][longest rally: 11], base64url.
export const ODDS_DATA = ${JSON.stringify({ games }, null, 0)};
`;
  writeFileSync(new URL('../src/odds-data.js', import.meta.url), out);

  const bot = (i) => OPPONENTS[i].bot;
  console.log('Single games (bot a vs bot b): a wins');
  for (const [key, t] of Object.entries(tally).sort()) {
    const [a, b] = key.split('-').map(Number);
    console.log(`  ${bot(a).padEnd(6)} vs ${bot(b).padEnd(6)} ${(100 * t.wins / t.n).toFixed(1).padStart(5)}%  (${t.wins}/${t.n})`);
  }
  if (validate) {
    console.log('Real best-of-3 / best-of-5 matches vs the single-game model:');
    for (const [a, b] of [[1, 2], [2, 3], [3, 4], [2, 2]]) {
      const t = tally[`${a}-${b}`];
      const g = a === b ? 0.5 : t.wins / t.n;
      for (const length of [2, 3]) {
        const rs = results.filter((x) => x.a === a && x.b === b && x.length === length);
        const n = rs.reduce((s, x) => s + x.n, 0), w = rs.reduce((s, x) => s + x.wins, 0);
        const model = length === 2 ? g * g * (3 - 2 * g) : g ** 3 * (10 - 15 * g + 6 * g * g);
        console.log(`  ${bot(a).padEnd(6)} vs ${bot(b).padEnd(6)} best of ${length * 2 - 1}: sims ${(100 * w / n).toFixed(1)}% (${w}/${n})  model ${(100 * model).toFixed(1)}%`);
      }
    }
  }
  console.log(`done in ${((Date.now() - t0) / 1000).toFixed(0)} s`);
}
